---

  - name: "TOWER TEST"
    hosts: cisco_devices
    gather_facts: false

    tasks:
      - name: "CONFIGURE NTP"
        cisco.ios.ios_config:
          lines:
            - "ntp server 1.1.1.1"
        register: ios_output
      
      - name: "PRINT OUTPUT"
        debug:
          msg: "{{ ios_output }}"

